### ISSUE TITLE
Crash if there is no directory with .gitignore file

### ISSUE THREAD

**Issue by dryganets** [g1eny0ung/electron-typescript-react-boilerplate#6]
Had to create project directory to workaround the crash during scaffolding.
```
---------------------------------------------------

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │ electron-typescript-reac │
   `---------´   │       t generator!       │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

---------------------------------------------------

? Type your app's name XXX
? Select a framework to use or not mobx
? Auto install dependencies by generator? (Y/n) y
```
Enter

```
You need to confirm some overwriting.
Error: /Users/s.dryganets/Snapchat/Dev/Test/XXX/.gitignore doesn't exist
    at EditionInterface.module.exports [as read] (/Users/s.dryganets/.nvm/versions/node/v14.2.0/lib/node_modules/yo/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at module.exports._copyCommonAddon (/Users/s.dryganets/.nvm/versions/node/v14.2.0/lib/node_modules/generator-electron-typescript-react/app/index.js:137:44)
    at module.exports.conflicts (/Users/s.dryganets/.nvm/versions/node/v14.2.0/lib/node_modules/generator-electron-typescript-react/app/index.js:91:10)
    at Object.<anonymous> (/Users/s.dryganets/.nvm/versions/node/v14.2.0/lib/node_modules/generator-electron-typescript-react/node_modules/yeoman-generator/lib/index.js:893:25)
    at /Users/s.dryganets/.nvm/versions/node/v14.2.0/lib/node_modules/generator-electron-typescript-react/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/s.dryganets/.nvm/versions/node/v14.2.0/lib/node_modules/generator-electron-typescript-react/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/s.dryganets/.nvm/versions/node/v14.2.0/lib/node_modules/generator-electron-typescript-react/node_modules/yeoman-generator/lib/index.js:894:11)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by g1eny0ung** [comment]
The operation of the generator will occur after the `create-react-app` is completed. Generally speaking, `create-react-app` will generate a `.gitignore` file.

I just tested it, but I didn't find this error. I guess it may be because the operation of create-react-app has not been completed, resulting in .gitignore is not written to the file system, so the generator can't read .gitignore?

**Comment by dryganets** [comment]
It might be an environment specific thing.

create-react-app --version
`3.4.1`

node --version
`v14.2.0`

It also maybe something in the way you test.

I'm using `mobx` framework.
If you are using the basic mode it will never get to checking the .gitignore file because of check :
```
 if (appFramework === 'basic') 
```

**Comment by g1eny0ung** [comment]
I still not produce this error by using `mobx` option. Here is the source code:

https://github.com/g1eny0ung/electron-typescript-react-boilerplate/blob/master/app/index.js#L133

```js
_copyCommonAddon() {
  this.fs.copy(this.templatePath('common-addon/.*'), this._getFileDestinationInProject(''))

  const gitIgnoreAppend = '\n/dist\n/app/node_modules\n/app/yarn.lock\n/app/package-lock.json'
  const originGitIgnoreContent = this.fs.read(this._getFileDestinationInProject('.gitignore'))

  if (!originGitIgnoreContent.includes(gitIgnoreAppend)) {
    this.fs.append(this._getFileDestinationInProject('.gitignore'), gitIgnoreAppend)
  }
}
```

As u can see, it will append something to the original `.gitignore` generated by `create-react-app` and the `create-react-app` will always generate `.gitignore` in the destination.
